### ISSUE TITLE
url in the mail of sign up with confirmation is wrong

### ISSUE THREAD

**Issue by paulywebster** [BenGorUser/UserBundle#44]
Hi,

I tried the sign-up with confirmation and the url contained in the sent mail is wrong.
The query string generated is ?token= .... and the query string expected is confirmation-token

It works when i change the parameter of the generate method into SymfonyUserUrlGenerator from "token" into "confirmation-token".

Sorry for my poor English.

**Comment by benatespina** [comment]
Hi @paulywebster,

we apologize for not answering before.
I've just published the [v0.8.4](https://github.com/BenGorUser/UserBundle/releases/tag/v0.8.4) release that solves this issue.

Thanks for your feedback!
